name: Release

on:
  push:
    # run only against tags
#    tags:
#      - 'v*'

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --force --tags

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.0'

      - name: Export GPG key
        run: |
          echo -n "${{ secrets.MAVEN_GPG_PRIVATE_KEY }}" > ./gpg.key

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          NFPM_PASSPHRASE: ${{ secrets.MAVEN_GPG_PRIVATE_KEY_PASSWORD }}
          NFPM_KEY_FILE: ./gpg.key
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: "Upload packages and invalidate artifacts cache"
#        if: github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main')
        run: |
          REPO_USER="${{ secrets.STEADYBIT_ARTIFACT_SERVER_USERNAME }}:${{ secrets.STEADYBIT_ARTIFACT_SERVER_PASSWORD }}"

          echo "Uploading deb packages to artifacts server"
          find ./target -name '*.deb' -type f -exec curl -u "$REPO_USER" -X POST -H "Content-Type: multipart/form-data" --data-binary "@{}" https://artifacts.steadybit.io/repository/deb-internal/ \;
          echo "Uploading rpm packages to artifacts server"
          find ./target -name '*.rpm' -type f -exec curl -u "$REPO_USER" --upload-file {} https://artifacts.steadybit.io/repository/yum-internal/ \;

          echo "Invalidating artifacts server cache"
          curl -X POST -u $REPO_USER https://artifacts.steadybit.io/service/rest/v1/repositories/yum-proxy/invalidate-cache
          curl -X POST -u $REPO_USER https://artifacts.steadybit.io/service/rest/v1/repositories/yum-public/invalidate-cache
          curl -X POST -u $REPO_USER https://artifacts.steadybit.io/service/rest/v1/repositories/deb-public/invalidate-cache
